/**
   @file musical_notes.h

   @brief contains all of the PSC values to play each piano key with a PWM signal.

   @see musical_frequencies.h
*/

#ifndef MUSICAL_NOTES_H
#define MUSICAL_NOTES_H

#include "musical_frequencies.h"
#include "musical_config.h"

/**
   @brief rounds a number at compile-time

   @param x some decimal number

   @returns a rounded integer
*/
#define COMPILE_TIME_ROUND(x) ((x) >= 0.0 ? (int)((x) + 0.5) : (int)((x) - 0.5))

/**
   @brief Finds the best PSC for a certain PWM frequency
   
   @param freq desired frequency (in Hertz)
   @param timer_freq TIM frequency (in Hertz)
   @param arr auto reload register from the TIM (a 16 bit unsigned int)

   @returns the PSC for the TIM to get the desired PWM frequency (a 16 bit unsigned int)
*/
#define FREQ_TO_PSC(freq, timer_freq, arr) COMPILE_TIME_ROUND(((timer_freq) / ((freq) * ((arr) + 1))) - 1)

/**
   @brief a data structure for a note

   @param psc the prescaler bit in the PWM parameters
   @param duration the musical length of a note in milliseconds
*/
typedef struct {

  uint32_t psc;
  uint32_t duration;

} note_t;

// These notes are the PSC values for generating PWM signals at each musical pitch

#define REST 0 // not a real PSC value. Check for 0 in the play_song function to set Duty Cycle to 0%
#define A0 FREQ_TO_PSC(A0_FREQ, TIM_FREQ, TIM_ARR)
#define A0_SHARP FREQ_TO_PSC(A0_SHARP_FREQ, TIM_FREQ, TIM_ARR)
#define B0_FLAT A0_SHARP
#define B0 FREQ_TO_PSC(B0_FREQ, TIM_FREQ, TIM_ARR)
#define C1 FREQ_TO_PSC(C1_FREQ, TIM_FREQ, TIM_ARR)
#define C1_SHARP FREQ_TO_PSC(C1_SHARP_FREQ, TIM_FREQ, TIM_ARR)
#define D1_FLAT C1_SHARP
#define D1 FREQ_TO_PSC(D1_FREQ, TIM_FREQ, TIM_ARR)
#define D1_SHARP FREQ_TO_PSC(D1_SHARP_FREQ, TIM_FREQ, TIM_ARR)
#define E1_FLAT D1_SHARP
#define E1 FREQ_TO_PSC(E1_FREQ, TIM_FREQ, TIM_ARR)
#define F1 FREQ_TO_PSC(F1_FREQ, TIM_FREQ, TIM_ARR)
#define F1_SHARP FREQ_TO_PSC(F1_SHARP_FREQ, TIM_FREQ, TIM_ARR)
#define G1_FLAT F1_SHARP
#define G1 FREQ_TO_PSC(G1_FREQ, TIM_FREQ, TIM_ARR)
#define G1_SHARP FREQ_TO_PSC(G1_SHARP_FREQ, TIM_FREQ, TIM_ARR)
#define A1_FLAT G1_SHARP
#define A1 FREQ_TO_PSC(A1_FREQ, TIM_FREQ, TIM_ARR)
#define A1_SHARP FREQ_TO_PSC(A1_SHARP_FREQ, TIM_FREQ, TIM_ARR)
#define B1_FLAT A1_SHARP
#define B1 FREQ_TO_PSC(B1_FREQ, TIM_FREQ, TIM_ARR)
#define C2 FREQ_TO_PSC(C2_FREQ, TIM_FREQ, TIM_ARR)
#define C2_SHARP FREQ_TO_PSC(C2_SHARP_FREQ, TIM_FREQ, TIM_ARR)
#define D2_FLAT C2_SHARP
#define D2 FREQ_TO_PSC(D2_FREQ, TIM_FREQ, TIM_ARR)
#define D2_SHARP FREQ_TO_PSC(D2_SHARP_FREQ, TIM_FREQ, TIM_ARR)
#define E2_FLAT D2_SHARP
#define E2 FREQ_TO_PSC(E2_FREQ, TIM_FREQ, TIM_ARR)
#define F2 FREQ_TO_PSC(F2_FREQ, TIM_FREQ, TIM_ARR)
#define F2_SHARP FREQ_TO_PSC(F2_SHARP_FREQ, TIM_FREQ, TIM_ARR)
#define G2_FLAT F2_SHARP
#define G2 FREQ_TO_PSC(G2_FREQ, TIM_FREQ, TIM_ARR)
#define G2_SHARP FREQ_TO_PSC(G2_SHARP_FREQ, TIM_FREQ, TIM_ARR)
#define A2_FLAT G2_SHARP
#define A2 FREQ_TO_PSC(A2_FREQ, TIM_FREQ, TIM_ARR)
#define A2_SHARP FREQ_TO_PSC(A2_SHARP_FREQ, TIM_FREQ, TIM_ARR)
#define B2_FLAT A2_SHARP
#define B2 FREQ_TO_PSC(B2_FREQ, TIM_FREQ, TIM_ARR)
#define C3 FREQ_TO_PSC(C3_FREQ, TIM_FREQ, TIM_ARR)
#define C3_SHARP FREQ_TO_PSC(C3_SHARP_FREQ, TIM_FREQ, TIM_ARR)
#define D3_FLAT C3_SHARP
#define D3 FREQ_TO_PSC(D3_FREQ, TIM_FREQ, TIM_ARR)
#define D3_SHARP FREQ_TO_PSC(D3_SHARP_FREQ, TIM_FREQ, TIM_ARR)
#define E3_FLAT D3_SHARP
#define E3 FREQ_TO_PSC(E3_FREQ, TIM_FREQ, TIM_ARR)
#define F3 FREQ_TO_PSC(F3_FREQ, TIM_FREQ, TIM_ARR)
#define F3_SHARP FREQ_TO_PSC(F3_SHARP_FREQ, TIM_FREQ, TIM_ARR)
#define G3_FLAT F3_SHARP
#define G3 FREQ_TO_PSC(G3_FREQ, TIM_FREQ, TIM_ARR)
#define G3_SHARP FREQ_TO_PSC(G3_SHARP_FREQ, TIM_FREQ, TIM_ARR)
#define A3_FLAT G3_SHARP
#define A3 FREQ_TO_PSC(A3_FREQ, TIM_FREQ, TIM_ARR)
#define A3_SHARP FREQ_TO_PSC(A3_SHARP_FREQ, TIM_FREQ, TIM_ARR)
#define B3_FLAT A3_SHARP
#define B3 FREQ_TO_PSC(B3_FREQ, TIM_FREQ, TIM_ARR)
#define C4 FREQ_TO_PSC(C4_FREQ, TIM_FREQ, TIM_ARR)
#define C4_SHARP FREQ_TO_PSC(C4_SHARP_FREQ, TIM_FREQ, TIM_ARR)
#define D4_FLAT C4_SHARP
#define D4 FREQ_TO_PSC(D4_FREQ, TIM_FREQ, TIM_ARR)
#define D4_SHARP FREQ_TO_PSC(D4_SHARP_FREQ, TIM_FREQ, TIM_ARR)
#define E4_FLAT D4_SHARP
#define E4 FREQ_TO_PSC(E4_FREQ, TIM_FREQ, TIM_ARR)
#define F4 FREQ_TO_PSC(F4_FREQ, TIM_FREQ, TIM_ARR)
#define F4_SHARP FREQ_TO_PSC(F4_SHARP_FREQ, TIM_FREQ, TIM_ARR)
#define G4_FLAT F4_SHARP
#define G4 FREQ_TO_PSC(G4_FREQ, TIM_FREQ, TIM_ARR)
#define G4_SHARP FREQ_TO_PSC(G4_SHARP_FREQ, TIM_FREQ, TIM_ARR)
#define A4_FLAT G4_SHARP
#define A4 FREQ_TO_PSC(A4_FREQ, TIM_FREQ, TIM_ARR) // 440
#define A4_SHARP FREQ_TO_PSC(A4_SHARP_FREQ, TIM_FREQ, TIM_ARR)
#define B4_FLAT A4_SHARP
#define B4 FREQ_TO_PSC(B4_FREQ, TIM_FREQ, TIM_ARR)
#define C5 FREQ_TO_PSC(C5_FREQ, TIM_FREQ, TIM_ARR)
#define C5_SHARP FREQ_TO_PSC(C5_SHARP_FREQ, TIM_FREQ, TIM_ARR)
#define D5_FLAT C5_SHARP
#define D5 FREQ_TO_PSC(D5_FREQ, TIM_FREQ, TIM_ARR)
#define D5_SHARP FREQ_TO_PSC(D5_SHARP_FREQ, TIM_FREQ, TIM_ARR)
#define E5_FLAT D5_SHARP
#define E5 FREQ_TO_PSC(E5_FREQ, TIM_FREQ, TIM_ARR)
#define F5 FREQ_TO_PSC(F5_FREQ, TIM_FREQ, TIM_ARR)
#define F5_SHARP FREQ_TO_PSC(F5_SHARP_FREQ, TIM_FREQ, TIM_ARR)
#define G5_FLAT F5_SHARP
#define G5 FREQ_TO_PSC(G5_FREQ, TIM_FREQ, TIM_ARR)
#define G5_SHARP FREQ_TO_PSC(G5_SHARP_FREQ, TIM_FREQ, TIM_ARR)
#define A5_FLAT G5_SHARP
#define A5 FREQ_TO_PSC(A5_FREQ, TIM_FREQ, TIM_ARR)
#define A5_SHARP FREQ_TO_PSC(A5_SHARP_FREQ, TIM_FREQ, TIM_ARR)
#define B5_FLAT A5_SHARP
#define B5 FREQ_TO_PSC(B5_FREQ, TIM_FREQ, TIM_ARR)
#define C6 FREQ_TO_PSC(C6_FREQ, TIM_FREQ, TIM_ARR)
#define C6_SHARP FREQ_TO_PSC(C6_SHARP_FREQ, TIM_FREQ, TIM_ARR)
#define D6_FLAT C6_SHARP
#define D6 FREQ_TO_PSC(D6_FREQ, TIM_FREQ, TIM_ARR)
#define D6_SHARP FREQ_TO_PSC(D6_SHARP_FREQ, TIM_FREQ, TIM_ARR)
#define E6_FLAT D6_SHARP
#define E6 FREQ_TO_PSC(E6_FREQ, TIM_FREQ, TIM_ARR)
#define F6 FREQ_TO_PSC(F6_FREQ, TIM_FREQ, TIM_ARR)
#define F6_SHARP FREQ_TO_PSC(F6_SHARP_FREQ, TIM_FREQ, TIM_ARR)
#define G6_FLAT F6_SHARP
#define G6 FREQ_TO_PSC(G6_FREQ, TIM_FREQ, TIM_ARR)
#define G6_SHARP FREQ_TO_PSC(G6_SHARP_FREQ, TIM_FREQ, TIM_ARR)
#define A6_FLAT G6_SHARP
#define A6 FREQ_TO_PSC(A6_FREQ, TIM_FREQ, TIM_ARR)
#define A6_SHARP FREQ_TO_PSC(A6_SHARP_FREQ, TIM_FREQ, TIM_ARR)
#define B6_FLAT A6_SHARP
#define B6 FREQ_TO_PSC(B6_FREQ, TIM_FREQ, TIM_ARR)
#define C7 FREQ_TO_PSC(C7_FREQ, TIM_FREQ, TIM_ARR)
#define C7_SHARP FREQ_TO_PSC(C7_SHARP_FREQ, TIM_FREQ, TIM_ARR)
#define D7_FLAT C7_SHARP
#define D7 FREQ_TO_PSC(D7_FREQ, TIM_FREQ, TIM_ARR)
#define D7_SHARP FREQ_TO_PSC(D7_SHARP_FREQ, TIM_FREQ, TIM_ARR)
#define E7_FLAT D7_SHARP
#define E7 FREQ_TO_PSC(E7_FREQ, TIM_FREQ, TIM_ARR)
#define F7 FREQ_TO_PSC(F7_FREQ, TIM_FREQ, TIM_ARR)
#define F7_SHARP FREQ_TO_PSC(F7_SHARP_FREQ, TIM_FREQ, TIM_ARR)
#define G7_FLAT F7_SHARP
#define G7 FREQ_TO_PSC(G7_FREQ, TIM_FREQ, TIM_ARR)
#define G7_SHARP FREQ_TO_PSC(G7_SHARP_FREQ, TIM_FREQ, TIM_ARR)
#define A7_FLAT G7_SHARP
#define A7 FREQ_TO_PSC(A7_FREQ, TIM_FREQ, TIM_ARR)
#define A7_SHARP FREQ_TO_PSC(A7_SHARP_FREQ, TIM_FREQ, TIM_ARR)
#define B7_FLAT A7_SHARP
#define B7 FREQ_TO_PSC(B7_FREQ, TIM_FREQ, TIM_ARR)
#define C8 FREQ_TO_PSC(C8_FREQ, TIM_FREQ, TIM_ARR)

#endif /* MUSICAL_NOTES_H */